name: esp_provisioning_example
description: Demonstrates how to use the esp_provisioning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esp_provisioning: 1.0.0+6
  flutter_bloc: ^7.0.0
  logger: ^1.0.0
  permission_handler: ^7.0.0
  equatable: ^2.0.5
  rxdart: ^0.26.0
  flutter_spinkit: ^5.0.0
  location: ^4.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

enable-experiment:
  - extension-methods
