name: esp_provisioning_example
description: Demonstrates how to use the esp_provisioning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esp_provisioning:
    path: ../
  flutter_bloc: ^3.2.0
  logger: ^0.8.3
  permission_handler: ^5.0.0+hotfix.3
  equatable: ^1.1.1
  rxdart: ^0.23.1
  flutter_spinkit: ^4.1.2+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

enable-experiment:
  - extension-methods